RDKCOM-2665 RDKBCMF-283 GwProvApp-EthWan Turris build failure
GwProvApp-EthWan build is failing:
| ccsp/GwProvApp-EthWan/source/gw_prov_ethwan_sm.c: In function 'GWPEthWan_linkstate_threadfunc':
| ccsp/GwProvApp-EthWan/source/gw_prov_ethwan_sm.c:703:77: error: ' | grep Link detected | cu...' directive writing 57 bytes into a region of size between 23 and 42 [-Werror=format-overflow=]
|   703 |     sprintf(command, ethtool %s | grep Link detected | cut -d ':' -f2 | cut -d ' ' -f2, wanPhyName);
|       |                                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~
| ccsp/GwProvApp-EthWan/source/gw_prov_ethwan_sm.c:703:5: note: 'sprintf' output between 66 and 85 bytes into a destination of size 50
|   703 |     sprintf(command, ethtool %s | grep Link detected | cut -d ':' -f2 | cut -d ' ' -f2, wanPhyName);
|       |     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
| cc1: all warnings being treated as errors
| Makefile:482: recipe for target 'gw_prov_ethwan-gw_prov_ethwan_sm.o' failed
| make[2]: *** [gw_prov_ethwan-gw_prov_ethwan_sm.o] Error 1

Reason for change: RDKBCMF-283 GwProvApp-EthWan Turris build failure
Test Procedure: None.
Risks: Low.
Signed-off-by: Stephen Barrett <stephen.barrett@accenture.com>

(cherry picked from commit 0c7f217028f92f50c8dbb3baf610a2e48703dba0)
Change-Id: Iad175837cfb19242906c806fb264f68723300509